name : Traditional EC2 Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Maven
        run : mvn clean package -DskipTests

      - name: Upload artifact to Ec2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username : ubuntu
          key: ${{ secrets.EC2_KEY}}
          source: "target/*.jar"
          target: "/home/ubuntu/"

      - name: Run jar on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST}}
          username : ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/target
            pkill -f "java -jar" || true
            nohup java -jar *.jar > app.log 2>&1 &
            echo "App deployed successfully!"
          